### PR TITLE
adds touch support

### PR DESCRIPTION
**Pull request by gobeli**
Quick fix for #26.
Maybe not the best approach (I just called the mouse events artificially on touch events). 
We could really use this in our project, but I understand if you don't want to add it, we would probably create another npm package then...

### CODE REVIEW

**Comment by IsraelZablianov** [comment]
Hi,
First of all great job!

here are several comments:

1. Touch support should be by default and not with 'allowTouch' flag.
2. As you said, you shouldn't call mouse events from the touch event. a better solution will be to refactor and extract the logic from 'mouse events' and use it in the touch events

**Comment by gobeli** [comment]
Thanks for the feedback I made some changes, namely, unified the touch and mouse events.

**Comment by IsraelZablianov** [comment]
Great work, I will go over it in the weekend

**Comment by gobeli** [comment]
Would you be able to merge it? We are currently just using a copy of the `draggable.ts` in our source code, but I think using the package would be cleaner...

**Pull request merged**
